config/routes.rb
Rails.application.routes.draw do

  resources :locations
  resources :charges
  resources :businesses
  resources :service_items
  resources :service_lists
  resources :web_viewer

  devise_for :users, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root 'web_viewer#index'

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:new, :show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    if signed_in?
      if current_user.business
        redirect_to action: "edit", id: current_user.business[:id]
      else
        redirect_to action: "new"
      end
    else
      redirect_to "/signin"
    end
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    if @business
      respond_to do |format|
        format.html { redirect_to action: edit, notice: 'You may only have one business.' }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
    @business = current_user.create_business
  end

  # GET /businesses/1/edit
  def edit

  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = current_user.business.create(business_params);
    @business.serviceValidTil = Time.now;


    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def signed_in?
    !current_user.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      if !signed_in?
        redirect_to "/signin"
      end

      @business = current_user.business
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:name, :summary, :tagLine, :domain, :logo, :service_list_name, :template)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%- model_class = Business -%>

<%= form_for( @business, multipart: true ,:html => { :class => "form-horizontal business" } )do |f| %>


    <%= image_tag @business.logo.url, size: "100", :class => 'img-rounded'%>

    <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@business[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :summary, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :summary, :class => 'form-control' %>
    </div>
    <%= error_span(@business[:summary]) %>
  </div>
  <div class="control-group">
    <%= f.label :tagLine, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tagLine, :class => 'form-control' %>
    </div>
    <%= error_span(@business[:tagLine]) %>
  </div>
  <div class="control-group">
    <%= f.label :domain, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :domain,:class => 'form-control' %>
    </div>
    <%= error_span(@business[:domain]) %>
  </div>

    <div class="control-group">
      <%= f.label :service_list_name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :service_list_name,:class => 'form-control' %>
      </div>
      <%= error_span(@business[:service_list_name]) %>
    </div>

    <div class="control-group">
      <%= f.label :template, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :template, [['Basic', 'web_viewer/index'],
                                 ['Material Paper', 'web_viewer/materialPaper']],
                     :class => 'form-control' %>
      </div>
      <%= error_span(@business[:template]) %>
    </div>

    <div class="field">
      <%= f.label :logo %>
      <%= f.file_field :logo %>
    </div>

  <%= f.submit "Save Changes", :class => 'btn btn-primary' %>

<% end %>

app/views/businesses/_form_hours.html.erb
<%- model_class = Business -%>

<%= simple_form_for( @business, multipart: true ,:html => { :class => 'form-horizontal business'} )do |f| %>

    <div class='row datetimerange'>
      <%= f.input :monday_hours, as: :time_picker, wrapper: :ranged_datetime %>
      <%= f.input :monday_hours_close, as: :time_picker, wrapper: :ranged_datetime %>
    </div>

    <div class='row datetimerange'>
      <%= f.input :tuesday_hours, as: :time_picker, wrapper: :ranged_datetime %>
      <%= f.input :tuesday_hours_close, as: :time_picker, wrapper: :ranged_datetime %>
    </div>

    <div class='row datetimerange'>
      <%= f.input :wednesday_hours, as: :time_picker, wrapper: :ranged_datetime %>
      <%= f.input :wednesday_hours_close, as: :time_picker, wrapper: :ranged_datetime %>
    </div>


    <div class='row datetimerange'>
      <%= f.input :thursday_hours, as: :time_picker, wrapper: :ranged_datetime %>
      <%= f.input :thursday_hours_close, as: :time_picker, wrapper: :ranged_datetime %>
    </div>

    <div class='row datetimerange'>
      <%= f.input :friday_hours, as: :time_picker, wrapper: :ranged_datetime %>
      <%= f.input :friday_hours_close, as: :time_picker, wrapper: :ranged_datetime %>
    </div>


    <div class='row datetimerange'>
      <%= f.input :saturday_hours, as: :time_picker, wrapper: :ranged_datetime %>
      <%= f.input :saturday_hours_close, as: :time_picker, wrapper: :ranged_datetime %>
    </div>


    <div class='row datetimerange'>
      <%= f.input :sunday_hours, as: :time_picker, wrapper: :ranged_datetime %>
      <%= f.input :sunday_hours_close, as: :time_picker, wrapper: :ranged_datetime %>
    </div>



    <%= f.submit "Save Changes", :class => 'btn btn-primary' %>

<% end %>

app/views/businesses/edit.html.erb
<%- model_class = Business -%>
<div class="page-header" xmlns="http://www.w3.org/1999/html">
  <h1><%= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<% if @business.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @business.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>

<div class="row">
  <div class="col-sm-4">
  </div>
  </div>
  <div class="col-sm-8" id = business_form>
    <%= render :partial => 'form' %>
  </div>
</div>


</div>

app/views/businesses/index.html.erb
<%- model_class = Business -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:summary) %></th>
      <th><%= model_class.human_attribute_name(:tagLine) %></th>
      <th><%= model_class.human_attribute_name(:serviceValidTil) %></th>
      <th><%= model_class.human_attribute_name(:domain) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= link_to business.id, business_path(business) %></td>
        <td><%= business.name %></td>
        <td><%= business.summary %></td>
        <td><%= business.tagLine %></td>
        <td><%= business.serviceValidTil %></td>
        <td><%= business.domain %></td>
        <td><%= business.user_id %></td>
        <td><%=l business.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_business_path(business), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      business_path(business),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_business_path,
            :class => 'btn btn-primary' %>

app/views/businesses/new.html.erb
<%- model_class = Business -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/businesses/show.html.erb
<%- model_class = Business -%>



<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<%= image_tag @business.logo.url, size: "100" %>
<dl class="dl-horizontal">


  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @business.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:summary) %>:</strong></dt>
  <dd><%= @business.summary %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tagLine) %>:</strong></dt>
  <dd><%= @business.tagLine %></dd>
  <dt><strong><%= model_class.human_attribute_name(:serviceValidTil) %>:</strong></dt>
  <dd><%= @business.serviceValidTil %></dd>
  <dt><strong><%= model_class.human_attribute_name(:domain) %>:</strong></dt>
  <dd><%= @business.domain %></dd>
  <dt><strong><%= model_class.human_attribute_name(:service_list_name) %>:</strong></dt>
  <dd><%= @business.service_list_name %></dd>
</dl>


<%= link_to t('.back', :default => t("helpers.links.back")),
              businesses_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_business_path(@business), :class => 'btn btn-default' %>