config/routes.rb
Rails.application.routes.draw do

  resources :locations
  resources :charges
  resources :businesses
  resources :service_items
  resources :service_lists
  resources :web_viewer

  devise_for :users, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root 'web_viewer#index'

end

app/models/service_list.rb
class ServiceList < ActiveRecord::Base
  has_many :service_items
end

app/controllers/service_lists_controller.rb
class ServiceListsController < ApplicationController
  before_action :set_service_list, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /service_lists
  # GET /service_lists.json
  def index
    @service_lists = current_user.business.service_lists.all
  end

  # GET /service_lists/1
  # GET /service_lists/1.json
  def show
  end

  # GET /service_lists/new
  def new
    @service_list = current_user.business.service_lists.new
  end

  # GET /service_lists/1/edit
  def edit
  end

  # POST /service_lists
  # POST /service_lists.json
  def create
    @service_list = current_user.business.service_lists.new(service_list_params)

    respond_to do |format|
      if @service_list.save
        format.html { redirect_to @service_list, notice: 'Service list was successfully created.' }
        format.json { render :show, status: :created, location: @service_list }
      else
        format.html { render :new }
        format.json { render json: @service_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_lists/1
  # PATCH/PUT /service_lists/1.json
  def update
    respond_to do |format|
      if @service_list.update(service_list_params)
        format.html { redirect_to @service_list, notice: 'Service list was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_list }
      else
        format.html { render :edit }
        format.json { render json: @service_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_lists/1
  # DELETE /service_lists/1.json
  def destroy
    @service_list.destroy
    respond_to do |format|
      format.html { redirect_to service_lists_url, notice: 'Service list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_list
      @service_list = current_user.business.service_lists.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_list_params
      params.require(:service_list).permit(:title, :rank, :comment)
    end
end

app/helpers/service_lists_helper.rb
module ServiceListsHelper
end

app/views/service_lists/_form.html.erb
<%= simple_form_for( @service_list, multipart: true ,:html => { :class => 'form-horizontal' }) do |f| %>
    <%= f.input :title %>
    <%= error_span(@service_list[:title]) %>
    <%= f.input :comment %>
    <%= error_span(@service_list[:comment]) %>
    <%= f.input :rank%>
    <%= error_span(@service_list[:rank]) %>

    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                service_items_path, :class => 'btn btn-default' %>
<% end %>

app/views/service_lists/edit.html.erb
<h1>Editing Service List</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_list %> |
<%= link_to 'Back', service_lists_path %>

app/views/service_lists/index.html.erb
<%- model_class = ServiceList -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:title) %></th>
    <th><%= model_class.human_attribute_name(:rank) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @service_lists.each do |service_list| %>
      <tr>
        <td><%= link_to service_list.id, service_list_path(service_list) %></td>
        <td><%= service_list.title %></td>
        <td><%= service_list.rank %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_service_list_path(service_list), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      service_list_path(service_list),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_service_list_path,
            :class => 'btn btn-primary' %>

app/views/service_lists/new.html.erb
<h1>New Service List</h1>

<%= render 'form' %>

<%= link_to 'Back', service_lists_path %>

app/views/service_lists/show.html.erb
<%- model_class = ServiceList -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @service_list.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
  <dd><%= @service_list.comment %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rank) %>:</strong></dt>
  <dd><%= @service_list.rank %></dd>
  <dt><strong><%= model_class.human_attribute_name(:business_id) %>:</strong></dt>
  <dd><%= @service_list.business_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
            service_lists_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_service_list_path(@service_list), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            service_list_path(@service_list),
            :method => 'delete',
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-danger' %>