config/routes.rb
Rails.application.routes.draw do

  resources :locations
  resources :charges
  resources :businesses
  resources :service_items
  resources :service_lists
  resources :web_viewer

  devise_for :users, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root 'web_viewer#index'

end

app/models/service_item.rb
class ServiceItem < ActiveRecord::Base
  belongs_to :business
  belongs_to :service_list
  validates :title, presence: true
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/service_items_controller.rb
class ServiceItemsController < ApplicationController
  before_action :set_service_item, only: [:show, :edit, :update, :destroy]
  before_action :set_list_items, only: [:edit, :new]
  before_filter :authenticate_user!

  # GET /service_items
  # GET /service_items.json
  def index
    @service_items = current_user.business.service_items.all
  end

  # GET /service_items/1
  # GET /service_items/1.json
  def show
  end

  # GET /service_items/new
  def new
    @service_item = current_user.business.service_items.new

  end

  # GET /service_items/1/edit
  def edit
  end

  # POST /service_items
  # POST /service_items.json
  def create
    @service_item = current_user.business.service_items.new(service_item_params)

    respond_to do |format|
      if @service_item.save
        format.html { redirect_to @service_item, notice: 'Service Item was successfully created.' }
        format.json { render :show, status: :created, location: @service_item }
      else
        format.html { render :new }
        format.json { render json: @service_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_items/1
  # PATCH/PUT /service_items/1.json
  def update
    respond_to do |format|
      if @service_item.update(service_item_params)
        format.html { redirect_to @service_item, notice: 'Service Items was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_item }
      else
        format.html { render :edit }
        format.json { render json: @service_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_items/1
  # DELETE /service_items/1.json
  def destroy
    @service_item.destroy

    respond_to do |format|
      format.html { redirect_to service_items_url, notice: 'Service Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_service_item
    @service_item = current_user.business.service_items.find(params[:id])

  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def service_item_params
    params.require(:service_item).permit(:title, :summary, :price, :service_list_id, :image)
  end

  def set_list_items
    @service_lists = current_user.business.service_lists.all;
  end

end

app/helpers/service_items_helper.rb
module ServiceItemsHelper
end

app/views/service_items/_form.html.erb
<%= simple_form_for( @service_item, multipart: true ,:html => { :class => 'form-horizontal' }) do |f| %>
    <%= image_tag @service_item.image.url, size: "100" %>

    <%= f.input :title %>
  <%= error_span(@service_item[:title]) %>
  <%= f.input :summary %>
  <%= error_span(@service_item[:summary]) %>
  <%= f.input :price%>
  <%= error_span(@service_item[:price]) %>
  <%= f.input :service_list_id, as: :select, collection: @service_lists %>
  <%= error_span(@service_item[:service_list_id]) %>
    <%= f.input :image, as: :file%>
    <%= error_span(@service_item[:image]) %>


    <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                service_items_path, :class => 'btn btn-default' %>
<% end %>

app/views/service_items/edit.html.erb
<%- model_class = ServiceItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/service_items/index.html.erb
<%- model_class = ServiceItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:summary) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:business_id) %></th>
      <th><%= model_class.human_attribute_name(:service_list_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @service_items.each do |service_item| %>
      <tr>
        <td><%= link_to service_item.id, service_item_path(service_item) %></td>
        <td><%= service_item.title %></td>
        <td><%= service_item.summary %></td>
        <td><%= service_item.price %></td>
        <td><%= service_item.business_id %></td>
        <td><%= service_item.service_list_id %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_service_item_path(service_item), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      service_item_path(service_item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_service_item_path,
            :class => 'btn btn-primary' %>

app/views/service_items/new.html.erb
<%- model_class = ServiceItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/service_items/show.html.erb
<%- model_class = ServiceItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<%= image_tag @service_item.image.url, size: "100" %>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @service_item.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:summary) %>:</strong></dt>
  <dd><%= @service_item.summary %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @service_item.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:business_id) %>:</strong></dt>
  <dd><%= @service_item.business_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:service_list_id) %>:</strong></dt>
  <dd><%= @service_item.service_list_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              service_items_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_service_item_path(@service_item), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              service_item_path(@service_item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>